TYPO3:

  Flow:
    security:
      authentication:
        providers:
          'Typo3BackendProvider':
            requestPatterns:
              'Wwwision\Neos\FrontendLogin\Security\NeosRequestPattern': 'backend'
          'FrontendLoginProvider':
            provider: 'PersistedUsernamePasswordProvider'
            requestPatterns:
              'Wwwision\Neos\FrontendLogin\Security\NeosRequestPattern': 'frontend'
            entryPoint: 'WebRedirect'
            entryPointOptions:
               # adjust this to the URI with the frontend login form
              uri: 'login.html'


  Neos:
    typoScript:
      autoInclude:
          # auto-include "Private/Resources/TypoScript/Root.ts2" from this package!
        'Wwwision.Neos.FrontendLogin': TRUE